### ISSUE TITLE
can't login with kajitool 

### ISSUE THREAD

**Issue by ena0** [RuntimeRacer/kajiwoto-dataset-tooling#3]
Hi, when I try to connect a kajiwoto with kajitool an error is displayed:

```go
Error: unable to login, response: "non-200 OK status code: 400 Bad Request body: \"{\\\"errors\\\":[{\\\"message\\\":\\\"Cannot query field \\\\\\\"settings\\\\\\\" on type \\\\\\\"Authentication\\\\\\\".\\\",\\\"locations\\\":[{\\\"line\\\":1,\\\"column\\\":327}],\\\"extensions\\\":{\\\"code\\\":\\\"GRAPHQL_VALIDATION_FAILED\\\"}}]}\\n\""
```

Is there a way to get the token directly from my kajiwoto account?

**Comment by RuntimeRacer** [comment]
Hi @ena0, I just updated the Kajiwoto SDK and updated Kajitool: https://github.com/RuntimeRacer/kajiwoto-dataset-tooling/commit/de33586b81cd866efa1fb0243a023f345730a0a6

You might need to run following commands locally in the folder where you put the source code to fix it:
go clean --modcache
go mod tidy

Then rebuild according to readme: https://github.com/RuntimeRacer/kajiwoto-dataset-tooling#building-kajitool

Please let me know if this fixed it for you.
